backend:
  name: github
  repo: Marhime/iziwork-landing
  branch: cms # Branch to update (optional; defaults to master)
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "topic"
    label: "Topic"
    folder: "src/pages/home/topics"
    create: true
    fields:
      - {
          label: "color",
          name: "color",
          widget: "select",
          options: ["blue", "yellow", "green"]
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Image", name: "featuredpost", widget: "image" }
      - { label: "Video Section", multiple: true, name: "videos", widget: "relation", collection: "videoSection", search_fields: [name], value_field: name}
  - name: "videoSection"
    label: "Video Section"
    folder: "src/pages/home/topics/videos"
    create: true
    fields:
      - { label: "Video Name", name: "name", widget: "string" }
      - { label: "Youtube Video ID", name: "videoID", widget: "string" }
      - { label: "PDF Section Title", required: false, name: "pdfSectionTitle", widget: "string" }
      - { label: "PDF",
          name: "pdfs",
          widget: "list",
          summary: '{{fields.title}}',
          collapsed: false,
          fields: [
            { label: "Title", name: "title", widget: "string" },
            { label: "Size", name: "size", widget: "string" },
            { label: "File", name: "file", widget: "file" },]
        }
      - { label: "Link Section Title", name: "linkSectionTitle", widget: "string", required: false }
      - { label: "Links", name: "link", widget: "list", summary: '{{fields.link}}', required: false, fields: [{label: Title, name: LinkTitle, widget: string}, {label: Link, name: link, widget: string}]}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page" }
          - { label: "Title", default: 'Con iziwork rispondi a tutte le tue <strong>domande</strong> riguardo', name: "homeTitle", widget: "string" }
          - { label: "Subtitle", default: "Scegli l’argomento", name: "homeSubtitle", widget: "string" }
          - { label: "Title Blog Section", default: "Il blog", name: "titleBlogSection", hint: "Title for the section blog", required: true, widget: "string" }